### ISSUE TITLE
Add support for other file managers e.g. vifm

### ISSUE THREAD

**Issue by ghost** [m45t3r/burgaur#2]
I suggest doing this by adding environmental variable `BURGAUR_FILE_MANAGER`.

**Comment by thiagokokada** [comment]
Ok, I can do it, but if I do this feature will be completely on the user responsability. Because there is some file managers (i.e. Nautilus) that simple returns after calling it, but burgaur expects a file manager that only returns after the user exit it. This is why I initially decided to implement this function to a specific file manager.

I this reasonable?

**Comment by ghost** [comment]
It works with terminal file managers, so this is good, thanks.
