### ISSUE TITLE
Change how/where packages are downloaded

### ISSUE THREAD

**Issue by ghost** [m45t3r/burgaur#5]
Rather than making a tmpdir in /var/tmp (_should only be used for persistent storage_), downloading to there, and then removing the directory, it should:
1. Ensure /tmp/burgaur exists
2. Download everything to /tmp/burgaur (no need for sanity checks, cower already does that)
3. Keep it there
This eliminates the need for `--nodelete` and `BURGAUR_TARGET_DIR` (`BUILDDIR` can be set if one doesn't want to build in a tmpfs).

**Comment by thiagokokada** [comment]
The problem of compiling things on `/tmp` is, since on Arch Linux it's mounted as a `tmpfs`, it would be easy to be in a OOM situation when compiling bigger packages like Firefox. [This page](https://lwn.net/Articles/499410/) discuss the problems of storing bigger files in `/tmp` as `tmpfs`. Burgaur ensures that after exiting it removes the temporary directory, even in case of errors*.

Your suggestion would be even worse than I do nowadays, because you could compile lots of small packages, that would continually occupy more RAM space until the system starts to crash because of OOM issues (or the user could not compile more packages in the case it sets a size limit for tmpfs, that is a better behavior but it's not common).

The variable `BURGAUR_TARGET_DIR` exists for exactly the user case when you want to change the default build location (you could add `BURGAUR_TARGET_DIR=/tmp` to your `.profile` or whatever). You could also `alias burgaur=burgaur --nodelete` too, so you would get a similar behavior you described in your post.

*: Yeah, I know this is not always the case (I had to test some cases and left my `/var/tmp` with some leftovers from previous package builds). But I think this shouldn't happen in normal use.

**Comment by ghost** [comment]
I guess that makes sense, it's just kind of annoying that whenever a build fails, `burgaur` just removes the directory, which has the sources, forcing me to redownload it. But I guess I'm just asking for pure `cower`.

**Comment by thiagokokada** [comment]
I could ask the user if he wants to delete the temporary directory, and maintain the current behavior in the case user pass `--noconfirm`. Is this ok?

If this is ok just reply and reopen the issue.

**Comment by ghost** [comment]
Yes, that sounds good

**Comment by thiagokokada** [comment]
Just did one small change with ef7c84e. In case the installation is sucessful, now `burgaur` delete the temporary directory without asking (as it was before d833381). But in case of error, we ask the user if he wants to delete the directory.

I think this cover your user case without making the default behavior worse (that is, asking unecessary things to the user). And yeah, I was somewhat fed up with the new behavior (asking for deleting for each new package).
